import { useEffect, useMemo, useState } from "react";
import { Check, CheckCircle2, Circle, Plus, Trash2, X } from "lucide-react";
import { auth } from "../../lib/firebase";
import { createTask, deleteTask, loadCachedTasks, loadTasks, migrateLegacyTasks, saveTasks } from "./taskService";
const filters=[["all","All"],["active","Active"],["today","Today"],["completed","Completed"]];
export default function TaskModule({onTasksChange}) {
 const uid=auth?.currentUser?.uid; const [tasks,setTasks]=useState(()=>loadCachedTasks(uid)); const [filter,setFilter]=useState("all"); const [draft,setDraft]=useState({title:"",priority:"normal",dueDate:"",scheduledTime:""}); const [error,setError]=useState("");
 useEffect(()=>{if(!uid)return undefined;let active=true;(async()=>{try{const cloud=await loadTasks(uid);const next=cloud.length?cloud:await migrateLegacyTasks(uid);if(active){setTasks(next);onTasksChange?.(next);}}catch{try{const migrated=await migrateLegacyTasks(uid);if(active){setTasks(migrated);onTasksChange?.(migrated);}}catch{if(active)setError("Cloud tasks are unavailable. Cached tasks remain available.");}}})();return()=>{active=false};},[uid,onTasksChange]);
 const today=new Date().toLocaleDateString("en-CA");
 const visible=useMemo(()=>{const open=tasks.filter(t=>!t.completed);if(filter==="active")return open;if(filter==="today")return open.filter(t=>t.dueDate===today||t.scheduledTime);if(filter==="completed")return tasks.filter(t=>t.completed);return tasks;},[filter,tasks,today]);
 async function commit(next){const previous=tasks;setTasks(next);onTasksChange?.(next);setError("");try{await saveTasks(uid,next,previous);}catch{setTasks(previous);onTasksChange?.(previous);setError("Unable to save this task. The previous state was restored.");}}
 function add(e){e.preventDefault();if(!draft.title.trim())return;void commit([createTask(draft.title,draft),...tasks]);setDraft({title:"",priority:"normal",dueDate:"",scheduledTime:""});}
 function toggle(task){const completed=!task.completed;void commit(tasks.map(item=>item.id===task.id?{...item,completed,status:completed?"completed":"active",updatedAt:new Date().toISOString()}:item));}
 async function remove(id){const previous=tasks,next=tasks.filter(t=>t.id!==id);setTasks(next);onTasksChange?.(next);try{await deleteTask(uid,id);}catch{setTasks(previous);onTasksChange?.(previous);setError("Unable to delete this task.");}}
 function updateTask(id,patch){void commit(tasks.map(task=>task.id===id?{...task,...patch,updatedAt:new Date().toISOString()}:task));}
 return <PageShell title="Tasks" subtitle="Plan, prioritize, and carry work into Today.">{error&&<p className="mb-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-200">{error}</p>}
 <form onSubmit={add} className="mb-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3"><div className="flex gap-2"><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Add a task…" className="min-w-0 flex-1 rounded-xl border border-[var(--border)] bg-transparent px-3 text-sm outline-none"/><button className="grid size-10 place-items-center rounded-xl bg-[var(--accent)] text-[var(--accent-contrast)]" aria-label="Add task"><Plus size={17}/></button></div>
 <div className="mt-2 grid gap-2 sm:grid-cols-3"><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})} className="min-h-9 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-2 text-xs"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select><input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})} className="min-h-9 rounded-lg border border-[var(--border)] bg-transparent px-2 text-xs" aria-label="Task due date"/><input type="time" value={draft.scheduledTime} onChange={e=>setDraft({...draft,scheduledTime:e.target.value})} className="min-h-9 rounded-lg border border-[var(--border)] bg-transparent px-2 text-xs" aria-label="Task scheduled time"/></div></form>
 <div className="mb-4 flex gap-1 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-1">{filters.map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={"flex-1 rounded-lg px-2 py-2 text-xs font-semibold "+(filter===id?"bg-[var(--surface-muted)]":"text-[var(--text-muted)]")}>{label}</button>)}</div>
 <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3">{visible.map(task=><TaskRow key={task.id} task={task} onToggle={()=>toggle(task)} onSave={patch=>updateTask(task.id,patch)} onDelete={()=>remove(task.id)}/>)}{!visible.length&&<p className="px-2 py-6 text-center text-xs text-[var(--text-muted)]">No tasks in this view.</p>}</div></PageShell>;
}
function TaskRow({task,onToggle,onSave,onDelete}){const [editing,setEditing]=useState(false);const [title,setTitle]=useState(task.title);return <div className="border-b border-[var(--border)] py-3 last:border-0"><div className="flex items-center gap-2"><button onClick={onToggle} aria-label={task.completed?"Reopen task":"Complete task"}>{task.completed?<CheckCircle2 size={18}/>:<Circle size={18} className="text-[var(--text-muted)]"/>}</button>{editing?<><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(onSave({title:title.trim()}),setEditing(false))} className="min-w-0 flex-1 rounded-lg border border-[var(--border)] bg-transparent px-2 py-1 text-sm outline-none"/><button onClick={()=>{onSave({title:title.trim()});setEditing(false)}} aria-label="Save task"><Check size={16}/></button><button onClick={()=>setEditing(false)} aria-label="Cancel edit"><X size={16}/></button></>:<button onClick={()=>setEditing(true)} className={"min-w-0 flex-1 text-left text-sm "+(task.completed?"text-[var(--text-muted)] line-through":"")}>{task.title}</button>} {!editing&&<button onClick={onDelete} aria-label="Delete task"><Trash2 size={15}/></button>}</div><div className="mt-1 pl-7 text-[10px] text-[var(--text-muted)]">{task.priority!=="normal"&&<span className="mr-2 uppercase">{task.priority}</span>}{task.dueDate&&<span className="mr-2">Due {task.dueDate}</span>}{task.scheduledTime&&<span>{task.scheduledTime}</span>}</div></div>}
function PageShell({title,subtitle,children}){return <section><header className="mb-5"><p className="label">DAYFLOW · TASKS</p><h2 className="mt-1 text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">{subtitle}</p></header>{children}</section>;}