import { useMemo, useState } from "react";
import { BookOpen, Search } from "lucide-react";
import { getDayFlowState } from "../../lib/dayflowStore";

function formatDate(key){return new Date(key+"T12:00:00").toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"});}
export default function MemoryModule(){
 const state=getDayFlowState(); const memories=Object.values(state.memories??{}).sort((a,b)=>b.date.localeCompare(a.date)); const [query,setQuery]=useState(""); const [range,setRange]=useState("all");
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return memories.filter(m=>{const matches=!q||String(m.note??"").toLowerCase().includes(q)||String(m.summary??"").toLowerCase().includes(q);if(range==="week"){const d=new Date(m.date+"T12:00:00"),cut=new Date();cut.setDate(cut.getDate()-7);return d>=cut&&matches;}return matches;});},[memories,query,range]);
 const stats=useMemo(()=>memories.slice(0,7).reduce((a,m)=>{const text=String(m.summary??"");const n=text.match(/(\d+) of (\d+)/);if(n){a.completed+=Number(n[1]);a.planned+=Number(n[2]);}return a;},{completed:0,planned:0}),[memories]);
 return <section><header className="mb-5"><p className="label">DAYFLOW · MEMORY</p><h2 className="mt-1 text-2xl font-bold">Memory</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Turn completed days into a searchable record.</p></header>
 <div className="mb-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><p className="label">REVIEWS</p><strong className="mt-1 block text-2xl">{memories.length}</strong></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><p className="label">LAST 7 DAYS</p><strong className="mt-1 block text-2xl">{stats.planned?Math.round(stats.completed/stats.planned*100):0}%</strong></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><p className="label">COMPLETED</p><strong className="mt-1 block text-2xl">{stats.completed}</strong></div></div>
 <div className="mb-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3"><div className="flex gap-2"><Search size={17} className="mt-2 text-[var(--text-muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search memories…" className="min-w-0 flex-1 bg-transparent py-2 text-sm outline-none"/></div><div className="mt-2 flex gap-1"><button onClick={()=>setRange("all")} className={"rounded-lg px-3 py-2 text-xs "+(range==="all"?"bg-[var(--surface-muted)]":"text-[var(--text-muted)]")}>All</button><button onClick={()=>setRange("week")} className={"rounded-lg px-3 py-2 text-xs "+(range==="week"?"bg-[var(--surface-muted)]":"text-[var(--text-muted)]")}>Last 7 days</button></div></div>
 <div className="grid gap-2">{filtered.map(memory=><article key={memory.date} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex items-start gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[var(--surface-muted)]"><BookOpen size={17}/></div><div><p className="label">{formatDate(memory.date).toUpperCase()}</p><p className="mt-2 text-sm">{memory.summary}</p>{memory.note&&<p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-[var(--text-muted)]">{memory.note}</p>}</div></div></article>)}{!filtered.length&&<div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 text-center text-xs text-[var(--text-muted)]">No memories match this view.</div>}</div>
 </section>;
}