import React,{useState} from "react";import{createRoot}from"react-dom/client";import{CalendarDays,CheckCircle2,Circle,Clock3,Home,Plus,BookOpen,Settings,Sun,ChevronRight,Brain,Target}from"lucide-react";import"./styles.css";
const events=[{time:"08:00",icon:"🏋️",title:"Morning training",meta:"45 min · Planned",done:true},{time:"10:00",icon:"💻",title:"Deep work",meta:"Project time · 2h",done:true},{time:"13:00",icon:"🍽️",title:"Lunch",meta:"Break · 1h",done:false},{time:"16:00",icon:"🚀",title:"DayFlow build",meta:"Product work · 90 min",done:false},{time:"20:00",icon:"📝",title:"Daily review",meta:"Memory · 15 min",done:false}];
const initialTasks=[["Finish DayFlow audit",true],["Review GitHub structure",true],["Define daily memory flow",false],["Connect existing To-Do",false]];
function App(){const[tasks,setTasks]=useState(initialTasks);const[tab,setTab]=useState("home");const[added,setAdded]=useState(false);const completed=tasks.filter(x=>x[1]).length;return <div className="shell"><header><div><span className="eyebrow">WEDNESDAY · SEP 30</span><h1>Good evening, Palmi <span>👋</span></h1><p>Your day, in one flow.</p></div><button className="avatar">P</button></header>
<main>{tab==="home"&&<><section className="hero"><div><span className="eyebrow">TODAY'S FLOW</span><strong>72%</strong><p>4 of 5 planned blocks on track</p></div><div className="ring"><span>72</span></div></section>
<section className="section"><div className="section-head"><h2>Today</h2><button>View calendar <ChevronRight size={16}/></button></div><div className="timeline">{events.map((e,i)=><div className={"event "+(e.done?"done":"")} key={e.time}><time>{e.time}</time><div className="event-card"><span className="event-icon">{e.icon}</span><div><b>{e.title}</b><small>{e.meta}</small></div>{e.done&&<CheckCircle2 size={19}/>}</div></div>)}</div></section>
<section className="section"><div className="section-head"><h2>Tasks <span>{completed}/{tasks.length}</span></h2><button onClick={()=>setAdded(true)}><Plus size={16}/> Add</button></div><div className="tasks">{tasks.map((t,i)=><button className="task" key={i} onClick={()=>setTasks(tasks.map((x,j)=>j===i?[x[0],!x[1]]:x))}>{t[1]?<CheckCircle2 className="checked"/>:<Circle/>}<span className={t[1]?"strike":""}>{t[0]}</span></button>)}{added&&<div className="new-task">✨ Ready for your next task.</div>}</div></section>
<section className="memory"><div className="memory-icon"><BookOpen size={20}/></div><div><span className="eyebrow">DAILY MEMORY</span><h2>Turn today's activity into a written memory.</h2><p>At the end of the day, DayFlow gathers what you planned and what actually happened.</p></div><button><ChevronRight size={18}/></button></section></>}
{tab==="calendar"&&<Empty icon={<CalendarDays/>} title="Calendar" text="Your planned blocks will live here."/>}{tab==="tasks"&&<Empty icon={<CheckCircle2/>} title="Tasks" text="Your unified To-Do will live here."/>}{tab==="memory"&&<Empty icon={<BookOpen/>} title="Memory" text="Your daily written memories will live here."/>}</main>
<nav>{[[Home,"home","Today"],[CalendarDays,"calendar","Calendar"],[CheckCircle2,"tasks","Tasks"],[BookOpen,"memory","Memory"]].map(([I,k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}><I size={21}/><span>{l}</span></button>)}</nav></div>}
function Empty({icon,title,text}){return <section className="empty"><div>{icon}</div><h2>{title}</h2><p>{text}</p></section>}createRoot(document.getElementById("root")).render(<App/>);